In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.mixture import GaussianMixture

# Get Data

In [3]:
train = pd.read_csv("Data/train_w_nan.csv", index_col = 0)
train.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f111,f112,f113,f114,f115,f116,f117,f118,claim,count_na
id,,,,,,,,,,,,,,,,,,,,,
0,0.10859,0.004314,-37.566,0.017364,0.28915,-10.25100,135.12,168900.0,3.992400e+14,86.489,...,1.7482,1.90960,-7.11570,4378.80,1.2096,8.613400e+14,140.100000,1.01770,1,1
1,0.10090,0.299610,11822.000,0.276500,0.45970,-0.83733,1721.90,119810.0,3.874100e+15,9953.600,...,4.1684,0.34808,4.14200,913.23,1.2464,7.575100e+15,1861.000000,0.28359,0,0
2,0.17803,-0.006980,907.270,0.272140,0.45948,0.17327,2298.00,360650.0,1.224500e+13,15827.000,...,1.2042,0.26290,8.13120,45119.00,1.1764,3.218100e+14,3838.200000,0.40690,1,5
3,0.15236,0.007259,780.100,0.025179,0.51947,7.49140,112.51,259490.0,7.781400e+13,-36.837,...,2.0694,0.79631,-16.33600,4952.40,1.1784,4.533000e+12,4889.100000,0.51486,1,2
4,0.11623,0.502900,-109.150,0.297910,0.34490,-0.40932,2538.90,65332.0,1.907200e+15,144.120,...,1.5298,1.14640,-0.43124,3856.50,1.4830,-8.991300e+12,3959.204669,0.23049,1,8

In [4]:
train.shape

(957919, 120)

In [5]:
test = pd.read_csv("Data/test.csv", index_col = 0)
test.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f109,f110,f111,f112,f113,f114,f115,f116,f117,f118
id,,,,,,,,,,,,,,,,,,,,,
957919,0.165850,0.487050,1295.00,0.02310,0.31900,0.90188,573.29,3743.7,2.705700e+12,6221.000,...,0.16253,-22.1890,2.0655,0.430880,-10.7410,81606.0,1.1940,1.980400e+14,2017.1,0.46357
957920,0.129650,0.373480,1763.00,0.72884,0.33247,-1.26310,875.55,554370.0,5.955700e+14,934.430,...,0.81528,-1.6342,1.5736,-1.071200,11.8320,90114.0,1.1507,4.388000e+16,6638.9,0.28125
957921,0.120190,0.445210,736.26,0.04615,0.29605,0.31665,2659.50,317140.0,3.977800e+14,131.810,...,0.81831,-32.7800,2.1364,-1.931200,-3.2804,37739.0,1.1548,1.718100e+14,5844.0,0.13797
957922,0.054008,0.395960,996.14,0.85934,0.36678,-0.17060,386.56,325680.0,-3.432200e+13,-26.473,...,0.86559,-2.4162,1.5199,-0.011633,1.3840,26849.0,1.1490,2.138800e+17,6173.3,0.32910
957923,0.079947,-0.006919,10574.00,0.34845,0.45008,-1.84200,3027.00,428150.0,9.291500e+11,5999.400,...,0.25190,-18.6300,3.7387,0.757080,-4.9405,50336.0,1.2488,2.151300e+17,2250.1,0.33796

In [6]:
test.shape

(493474, 118)

# Per feature check if it is multimodal

In [11]:
n_modes_per_feature = dict()

aics_per_feature = dict()
bics_per_feature = dict()

for i in range(1, 119):
    
    feature_name = f"f{i}"
    
    aics = []
    bics = []
    
    X = train[[feature_name]].dropna()
    
    for n_components in range(1, 6):
    
        gmm = GaussianMixture(n_components)
        gmm.fit(X)
        
        aics.append(gmm.aic(X))
        bics.append(gmm.bic(X))
        
    ideal_n_components = np.argmin(aics) + 1
    
    n_modes_per_feature[feature_name] = ideal_n_components
    aics_per_feature[feature_name] = aics
    bics_per_feature[feature_name] = bics

In [13]:
aics_per_feature['f1']

[-3300246.3613038464,
 -3297146.751896018,
 -3430299.544208436,
 -3434078.5853733923,
 -3477334.4291125475]

In [14]:
bics_per_feature['f1']

[-3300222.8162668417,
 -3297087.889303507,
 -3430205.3640604177,
 -3433949.087669868,
 -3477169.6138535165]

In [12]:
n_modes_per_feature

{'f1': 5,
 'f2': 5,
 'f3': 5,
 'f4': 5,
 'f5': 5,
 'f6': 4,
 'f7': 5,
 'f8': 5,
 'f9': 5,
 'f10': 5,
 'f11': 5,
 'f12': 5,
 'f13': 3,
 'f14': 5,
 'f15': 5,
 'f16': 5,
 'f17': 5,
 'f18': 5,
 'f19': 5,
 'f20': 4,
 'f21': 5,
 'f22': 4,
 'f23': 4,
 'f24': 5,
 'f25': 5,
 'f26': 5,
 'f27': 5,
 'f28': 5,
 'f29': 5,
 'f30': 5,
 'f31': 5,
 'f32': 4,
 'f33': 4,
 'f34': 5,
 'f35': 5,
 'f36': 5,
 'f37': 5,
 'f38': 5,
 'f39': 5,
 'f40': 5,
 'f41': 5,
 'f42': 5,
 'f43': 3,
 'f44': 5,
 'f45': 5,
 'f46': 5,
 'f47': 5,
 'f48': 4,
 'f49': 5,
 'f50': 5,
 'f51': 4,
 'f52': 5,
 'f53': 5,
 'f54': 5,
 'f55': 4,
 'f56': 5,
 'f57': 5,
 'f58': 4,
 'f59': 5,
 'f60': 5,
 'f61': 5,
 'f62': 5,
 'f63': 5,
 'f64': 5,
 'f65': 5,
 'f66': 4,
 'f67': 5,
 'f68': 5,
 'f69': 5,
 'f70': 5,
 'f71': 5,
 'f72': 5,
 'f73': 5,
 'f74': 5,
 'f75': 5,
 'f76': 5,
 'f77': 5,
 'f78': 5,
 'f79': 4,
 'f80': 4,
 'f81': 5,
 'f82': 5,
 'f83': 5,
 'f84': 5,
 'f85': 5,
 'f86': 5,
 'f87': 5,
 'f88': 5,
 'f89': 5,
 'f90': 4,
 'f91': 5,
 'f92': 5,
 'f93': 5,
 'f94': 4,
 'f95': 5,
 'f96': 4,
 'f97': 5,
 'f98': 5,
 'f99': 4,
 'f100': 5,
 'f101': 5,
 'f102': 5,
 'f103': 5,
 'f104': 5,
 'f105': 5,
 'f106': 5,
 'f107': 5,
 'f108': 5,
 'f109': 4,
 'f110': 5,
 'f111': 5,
 'f112': 5,
 'f113': 4,
 'f114': 5,
 'f115': 5,
 'f116': 5,
 'f117': 5,
 'f118': 5}